### ISSUE TITLE
Exception org.apache.kafka.connect.errors.DataException: Kafka Connect Date type should not have any time fields set to non-zero values

### ISSUE THREAD

**Issue by brunodomenici** [SAP/kafka-connect-sap#7] opened 2018-07-12 13:48 UTC
Hi,

I'm trying to configure a **kafka-connect-sap** as a source and I'm receiving this error:

```
[2018-07-11 17:56:43,151] INFO Closing this query for IncrColTableQuerier{name='"_SYS_BIC"."XXXX"', topic='XXX'} (com.sap.kafka.connect.source.hana.HANASourceTask:165)
[2018-07-11 17:56:43,151] INFO Returning 100 records for IncrColTableQuerier{name='"_SYS_BIC"."XXX"', topic='lmb_flash_venda'} (com.sap.kafka.connect.source.hana.HANASourceTask:177)
[2018-07-11 17:56:43,161] INFO WorkerSourceTask{id=kafka-connect-source-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:328)
[2018-07-11 17:56:43,162] INFO WorkerSourceTask{id=kafka-connect-source-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:345)
[2018-07-11 17:56:43,162] ERROR WorkerSourceTask{id=kafka-connect-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.DataException: Kafka Connect Date type should not have any time fields set to non-zero values.
    at org.apache.kafka.connect.data.Date.fromLogical(Date.java:64)
    at io.confluent.connect.avro.AvroData$6.convert(AvroData.java:272)
    at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:380)
    at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:565)
    at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:326)
    at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:74)
    at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:228)
    at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:194)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
[2018-07-11 17:56:43,164] ERROR WorkerSourceTask{id=kafka-connect-source-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
```
My config:

```
name=kafka-connect-source
connector.class=com.sap.kafka.connect.source.hana.HANASourceConnector
tasks.max=1

topics=lmb_flash_venda
connection.url=XXX
connection.user=XXX
connection.password=XXX
#queryMode=query
mode=incrementing

lmb_flash_venda.table.name="_SYS_BIC"."lmb.query/LMB_FLASH_VENDA"
lmb_flash_venda.partition.count=5
lmb_flash_venda.poll.interval.ms=60000
lmb_flash_venda.incrementing.column.name=TimestampTS

```
Any sugestion?
Thank you

**Comment by sbcd90** [comment] 2018-08-29 18:26
Hi @brunodomenici ,
i think this is a kafka issue
https://github.com/axbaretto/kafka/blob/master/connect/api/src/main/java/org/apache/kafka/connect/data/Date.java#L62-#L65

Can you please specify some sample data which is used in table _SYS_BIC"."XXXX" ?

**Comment by Satya2188** [comment] 2019-03-19 17:29
Hi @sbcd90 
I'm also getting the same issue while using Time.fromLogical(org.apache.kafka.connect.data.Time.SCHEMA, date);

My Input is : Tue Mar 19 23:13:29 IST 2019

Caused by: org.apache.kafka.connect.errors.DataException: Kafka Connect Time type should not have any date fields set to non-zero values.
	at org.apache.kafka.connect.data.Time.fromLogical(Time.java:64)
	at com.aiotal.ezflow.utils.TimestampConverterUtilty.timestampOpeartions(TimestampConverterUtilty.java:152)
	at com.aiotal.ezflow.main.TimestampConverter$1.apply(TimestampConverter.java:101)
	at com.aiotal.ezflow.main.TimestampConverter$1.apply(TimestampConverter.java:1)
	at org.apache.kafka.streams.kstream.internals.AbstractStream$2.apply(AbstractStream.java:127)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:40)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.forward(AbstractProcessorContext.java:174)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:224)
	... 6 more

Any suggestion?
Thank you

**Comment by elakito** [comment] 2020-09-24 09:30
This problem has been fixed with https://github.com/SAP/kafka-connect-sap/pull/39.

**Closed by elakito** 2020-09-24 09:30 UTC
Labels: bug
