### ISSUE TITLE
with mode bulk same data is pulled ricorsiverly

### ISSUE THREAD

**Issue by Sano123456** [SAP/kafka-connect-sap#15] opened 2018-11-22 14:51 UTC
I am using the bulk mode but the connector retrive the same data everytime without going farther with new data
is this normal?

**Comment by Sano123456** [comment] 2018-11-26 10:23
Hello @sbcd90 
this is my configuration 
{
    "name": "sap",
    "config": {
        "connector.class": "com.sap.kafka.connect.source.hana.HANASourceConnector",
        "tasks.max": "10",
        "topics": "sap_OHEM,sap_OHST",
        "connection.url": "jdbc:sap://10.236.242.1:30015/",
        "connection.user": "user",
        "connection.password": "pass",
        "mode":"bulk",
        "poll.interval.ms":"86400000",
        "sap_OHEM.table.name":                          "\"public\".\"OHEM\"",
        "sap_OHEM.poll.interval.ms":                    "86400000",
        "sap_OHST.table.name":                          "\"public\".\"OHST\"",
        "sap_OHST.poll.interval.ms":                    "86400000",
    }
}

OHEM has over 300K rows and OHST has about 500. 
My problem is that the connector copy just 100 rows of each of them and push them to the topic over adn over again without duing an incremental step. It doesn't copy all the table but just 100 rows of it and than copy it agin and again.
I tried with **batch.max.rows** putting 100K as limit, this solved the problem with small tables but not with big tables because it broke JVM memory

I hope i described better the problem

**Comment by twonly** [comment] 2021-01-21 08:24
I have observed the same problem in my case. The first 100 rows were retrieved and put into the topic again and again.

**Comment by twonly** [comment] 2021-01-21 08:55
> I am using the bulk mode but the connector retrive the same data everytime without going farther with new data
> is this normal?



> Hello @sbcd90
> this is my configuration
> {
> "name": "sap",
> "config": {
> "connector.class": "com.sap.kafka.connect.source.hana.HANASourceConnector",
> "tasks.max": "10",
> "topics": "sap_OHEM,sap_OHST",
> "connection.url": "jdbc:sap://10.236.242.1:30015/",
> "connection.user": "user",
> "connection.password": "pass",
> "mode":"bulk",
> "poll.interval.ms":"86400000",
> "sap_OHEM.table.name": ""public"."OHEM"",
> "sap_OHEM.poll.interval.ms": "86400000",
> "sap_OHST.table.name": ""public"."OHST"",
> "sap_OHST.poll.interval.ms": "86400000",
> }
> }
> 
> OHEM has over 300K rows and OHST has about 500.
> My problem is that the connector copy just 100 rows of each of them and push them to the topic over adn over again without duing an incremental step. It doesn't copy all the table but just 100 rows of it and than copy it agin and again.
> I tried with **batch.max.rows** putting 100K as limit, this solved the problem with small tables but not with big tables because it broke JVM memory
> 
> I hope i described better the problem

Even if the parameter **batch.max.rows** is set as 100K, the source will still retrieve the first 100K record for times till the process stopped.

**Comment by elakito** [comment] 2021-01-21 18:00
@twonly I am not sure if there is some confusion here. The `bulk` mode is meant to repeatedly pull up to the amount of rows set by `batch.max.rows`, whose default value is 100. So, whatever the value is set, the source connector will simply pull up to that amount of records each interval. So, the repeated retrieval is not the problem here. If you want only the added rows to be pulled, you have to use the `incrementing` mode.

The limitation of the current approach mentioned by @Sano123456  is that the connector does not allow an incremental load of a large table, which we should actually be supporting for.

**Comment by twonly** [comment] 2021-01-22 00:31
@elakito thanks for clarification. I believe I have the same (similar) problem as @Sano123456  here, as though I have a table with 1000 records, and if I have the default `batch.max.rows` (which is 100), then the source connector would retrieve the first 100 records time after time. 
In my case, `incrementing` mode would be more suitable. And I have now configured it successfully in my env. However, is it required for the `incrementing column(s)` to be a primary key so the incrementing would work normally?

**Comment by elakito** [comment] 2021-01-22 07:41
@twonly When using the incrementing column doesn't need to be a primary key but ideally of some numeric or date/time types so that the ordering (incrementing order) is obvious. You could use a string based column, the values should use a fixed width so that, for example, 9 and 10 are correctly ordered as 009 and 010 and not the other way around as lexicographically compared. If you encounter some problem using the incrementing mode, please open a separate issue. Thanks.

**Comment by venky2100b** [comment] 2021-02-01 11:32
Can I load 50 million records from Hana to Cassandra using bulk mode once a week?

I have 50 million records In the Hana table, There is no timestamp or date column while updating any record. Then I tried with bulk mode option to send the data from Hana to Cassandra but after sending all 50 million records to the topic it is not stopping to send the data to the topic and continuously polling and not sending data to Cassandra. can we stop the polling data to the topic after 50 million records sent and send once a week?

How can we achieve this requirement. can anyone suggest the best option if it is not possible with bulk mode.


`  {    "name": "apo_rule_source",
    "config": {  
      "connector.class": "com.sap.kafka.connect.source.hana.HANASourceConnector",
      "connection.password": "****",
      "queryMode": "query",
      "tasks.max": "1",
      "topics":"apo_rule_topic",
      "apo_rule_topic.query": "SELECT * FROM \"_SYS_BIC\".\"sial.com.availability.datamodels/ZAPO\"",
      "connection.attempts": "4",
      "transforms.extractInt.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
      "batch.max.rows": "20000",
      "apo_rule_topic.table.name":"\"_SYS_BIC\".\"sial.com.availability.datamodels/ZAPO\"",
      "mode": "bulk",
      "connection.user": "******",
      "apo_rule_topic.poll.interval.ms": "5000",
      "name": "apo_rule_source",
      "connection.url": "jdbc:sap://:*******/"
    }
}`

**Comment by elakito** [comment] 2021-02-02 23:29
@venky2100b You can set the interval to 1 week msec or have just a large value and use the API to pause the task except for the time when the job should run once a week.
By the way, am I right to assume that you are using the master snapshot?

**Comment by venky2100b** [comment] 2021-02-03 10:38
@elakito thanks for the reply.
If I set interval ["apo_rule_topic.poll.interval.ms": "5000"] to maximum time I only get the first 20k records to Cassandra once a week.

My requirement is just to store all 5 million records to Cassandra once every week.

**Comment by elakito** [comment] 2021-02-03 15:35
The patch (https://github.com/SAP/kafka-connect-sap/pull/66 ) for the problem mentioned in this ticket, namely the problem of not retrieving all records, hasn't been merged to master. So the current master snapshot still has this problem and retrieves only batch.max.rows records. So, I'll merge this PR so that all records are incrementally retrieved. Could you try this version?

**Comment by elakito** [comment] 2021-02-03 17:29
Now the patch is in master and I suppose the problem is resolved. Unless someone still reports this problem with this version, I'll close this ticket. If you encounter another issue, please open a new ticket that is specific to that problem. Thanks.

**Closed** 2021-02-15 18:57 UTC
